### ISSUE TITLE
Code issue when validating the test vectorf for MOPS Aircraft and Control Model

### ISSUE THREAD

**Issue by HonJinghua** [mitre/FMACM#5] opened 2015-07-07 02:50 UTC
When running A/C model test vectors,  the following four issues were found. All the A/C Model test vectors can run pass with the corrections in the code below.

1)  In BadaWithCalc::getMaxThrust() in BadaWithCalc.cpp,  the input parameter “h” is meter, but Transition altitude, etc in struct engine_thrust are feet. So the input parameter "h" should be converted to feet.  

2)  In function BadaWithCalc::getConfigForDrag() , the input parameter "double alt" and the variable "altAtFAF" are defined as meter, it should be converted to feet in this function per defination in MOPS Appendix H (Algorithm H.8 Get Configuration for Increased Drag).

3)  In function StateModel::init() in StateModel.cpp, the finalAltitude was set to the first h_ref[m] in VFP.
void ThreeDOFDynamics::init(double mass_percentile, Units::MetersLength altAtFAF_in, …)
{
    …
    altAtFAF = Units::MetersLength(altAtFAF_in);

In FimAcTv-T~W_JET6_VFP.csv, the first h_ref[m] was set as finalAltitude (3962meters). This will set the FAF to 10000ft, where the flap will be changed in BadaWithCalc::getConfigForDrag(), so the test FimAcTv-T~W _JET6 failed. 
TTG[sec]    DTG[m]  h_ref[m]    Vias_ref[m/s]   hdot_ref[m/s]
0   0   3962.399994 87.45556    0

Current our solution is hardcoded with altAtFAF with 3000feet. 

4)  The vector preCal_Wpt  in FlightManagementSystem::update() in FlightManagementSystem.cpp are pushed from HPT_1 to HPT_8. So the constraint_dist are vectored starting from the endpoint in function TrajectoryFromFile::calculateWaypoints() . So precalcWaypoints[ix].constraints.constraint_dist is greater than precalcWaypoints[ix-1].constraints.constraint_dist, the condition below will always be failed. 

   for (int ix = 1;(ix<precalcWaypoints.size());ix++) {
   if ((currDist < precalcWaypoints[ix-1].constraints.constraint_dist) &&
          (currDist >= precalcWaypoints[ix].constraints.constraint_dist)) 
    {
        this->NextWp = ix;
        break;
    }

Current our solution is 
    for (int ix = 1;(ix<precalcWaypoints.size());ix++) {
      if ((currDist >= precalcWaypoints[ix-1].constraints.constraint_dist) &&
          (currDist < precalcWaypoints[ix].constraints.constraint_dist)) 
    {
           this->NextWp = 8-ix;
           break;
      }

**Comment by sbowman-mitre** [comment] 2015-07-07 13:50
Hi @HonJinghua : 
1) Yes, that unit conversion is correct.
2) Yup, that unit conversion is also correct.
3) Hmm.....I'm not comfortable with your hard-coded solution. I re-ran this test case & do not find any problems with the final output. In our simulation, the aircraft switched drag modes (from 0 to 1) at around alt = 4025 meters. The transition was triggered because v_cas dropped below the BADA approach max speed. Please re-examine your implementation to see if you missed anything in the getConfigForDrag calculation.
4) I'm not sure about this one. I will need to examine it more thoroughly before I can respond.

**Comment by HonJinghua** [comment] 2015-07-08 10:21
For #3,we find the root cause. The implementation for getConfigForDrag per MOPS Algorithm H.8. For JET6, but the JET6 additional parameter defined in MOPS table G-5 in Appendix G are not set into BADA data. 
The original data in BADA data parameters are set to 0 by default, why not put into BADA data directly? the other vendor will not meet this kind of issue:)

**Comment by sbowman-mitre** [comment] 2015-07-08 13:40
Good, I'm glad you were able to find the root cause!

Yes, you are correct that JET6 has an extra parameter value that is NOT provided by EUROCONTROL. That data is provided by a separate organization and so is outside of our control. We cannot modify it for you, which is why it was specifically mentioned in the MOPS Appendix G. I'm glad your simulations are working better for you now. I'll close this comment now.

**Comment by sbowman-mitre** [comment] 2015-07-08 13:41
Sorry, just realize this was the wrong one to close. I've reopened it and will provide an answer for 4) above soon.

**Comment by HonJinghua** [comment] 2015-07-08 13:45
Stuart,

For the #3, do you think if JET6 additional parameter can be included in BADA Data as well? So maybe other vendors don’t need to further investigate this issue if not aware of this at beginning.

Thanks,
Jinghua

**Comment by sbowman-mitre** [comment] 2015-07-08 14:09
Well, as I've already stated, we don't have control over that data. But, we can bring up your concern with the committee and we will do that soon.

**Comment by sbowman-mitre** [comment] 2015-07-08 15:13
@HonJinghua : I'm going to turn question 4) above into new issue #6 and close this one.

**Closed as completed by sbowman-mitre** 2015-07-08 15:13 UTC
